instance:
  _target_: teleoperation.camera.camera_oak.CameraOak
  key: "top"
  fps: 30
  use_depth: ${use_depth}
  stereo_resolution: "720p"
  color_resolution: "1080p"

  save_processes: 8
  save_threads: 4
  save_queue_size: 30

  display_mode: "stereo"
  display_resolution: [720, 1280]
  display_crop_sizes: [0, 0, 0, 0]
