instance:
  _target_: teleoperation.camera.camera_oak.CameraOak
  key: "top"
  fps: 60
  use_depth: ${use_depth}
  stereo_resolution: "800p"
  color_resolution: "800p"

  display_mode: "stereo"
  display_resolution: [800, 1280]
  display_crop_sizes: [0, 0, 0, 0]
