left_hip_roll_joint_encoder:
  calibration_pose: 92.5048828125
  poweron_pose: 142.8662109375
  joint_name: left_hip_roll_joint
left_hip_yaw_joint_encoder:
  calibration_pose: 239.78759765625
  poweron_pose: 353.7158203125
  joint_name: left_hip_yaw_joint
left_hip_pitch_joint_encoder:
  calibration_pose: 18.91845703125
  poweron_pose: 233.98681640625
  joint_name: left_hip_pitch_joint
left_knee_pitch_joint_encoder:
  calibration_pose: 172.7490234375
  poweron_pose: 166.7724609375
  joint_name: left_knee_pitch_joint
left_ankle_pitch_joint_encoder:
  calibration_pose: 159.49951171875
  poweron_pose: 199.2919921875
  joint_name: left_ankle_pitch_joint
left_ankle_roll_joint_encoder:
  calibration_pose: 275.29541015625
  poweron_pose: 92.373046875
  joint_name: left_ankle_roll_joint
right_hip_roll_joint_encoder:
  calibration_pose: 246.73095703125
  poweron_pose: 242.42431640625
  joint_name: right_hip_roll_joint
right_hip_yaw_joint_encoder:
  calibration_pose: 14.69970703125
  poweron_pose: 47.13134765625
  joint_name: right_hip_yaw_joint
right_hip_pitch_joint_encoder:
  calibration_pose: 235.08544921875
  poweron_pose: 72.48779296875
  joint_name: right_hip_pitch_joint
right_knee_pitch_joint_encoder:
  calibration_pose: 239.5458984375
  poweron_pose: 275.5810546875
  joint_name: right_knee_pitch_joint
right_ankle_pitch_joint_encoder:
  calibration_pose: 101.79931640625
  poweron_pose: 95.80078125
  joint_name: right_ankle_pitch_joint
right_ankle_roll_joint_encoder:
  calibration_pose: 103.271484375
  poweron_pose: 122.18994140625
  joint_name: right_ankle_roll_joint
waist_yaw_joint_encoder:
  calibration_pose: 323.28369140625
  poweron_pose: 138.2958984375
  joint_name: waist_yaw_joint
waist_pitch_joint_encoder:
  calibration_pose: 77.98095703125
  poweron_pose: 109.951171875
  joint_name: waist_pitch_joint
waist_roll_joint_encoder:
  calibration_pose: 355.49560546875
  poweron_pose: 228.66943359375
  joint_name: waist_roll_joint
