urdf_path: "urdf/qinglong_fourier_hand_6dof.urdf"
urdf_package_dirs: ["urdf"]
# urdf_path: "gr1_inspire/urdf/t2_collision.urdf"
# urdf_package_dirs: ["gr1_inspire/urdf"]

controlled_joint_indices: "${eval:'list(range(5, 19))'}"
# default_qpos: "${eval:'np.array([
#     -np.pi / 12, 0.2, 0, np.pi / 2, 0, 0, 0,
#     -np.pi / 12, 0.2, 0, np.pi / 2, 0, 0, 0])'}"
default_qpos: "${eval:'np.array([
  0, 1.3, 1.6, 1.6, 0, 0, 0,
  0, 1.3, -1.6, 1.6, 0, 0, 0])'}"


joint_names:
  [
    "J_waist_pitch",
    "J_waist_roll",
    "J_waist_yaw",

    "J_head_yaw",
    "J_head_pitch",

    "J_arm_l_01",
    "J_arm_l_02",
    "J_arm_l_03",
    "J_arm_l_04",
    "J_arm_l_05",
    "J_arm_l_06",
    "J_arm_l_07",

    "J_arm_r_01",
    "J_arm_r_02",
    "J_arm_r_03",
    "J_arm_r_04",
    "J_arm_r_05",
    "J_arm_r_06",
    "J_arm_r_07",
  ]
visualize: false
debug: ${debug}
debug_hand: ${debug_hand}
display_collisions: false
displayed_frames:
  # - "right_ee_frame"
  # - "left_ee_frame"
  - "R_hand_base_link"
  - "R_hand_camera_frame_link"
  - "L_hand_base_link"
  - "left_end_effector_link"
  # - "L_hand_camera_frame_link"
  - "link_base"
  - "Link_head_pitch"

self_collision:
  enable: false
  min_distance: 0.02
  enabled_links: []

joints_to_lock: [
    "J_waist_roll",
    "J_waist_yaw",
  ]

waist_joints: ["J_waist_pitch"]
head_joints: ["J_head_yaw", "J_head_pitch"]

# frames:
#   - name: "right_end_effector_link"
#     parent: "right_hand_roll_link"
#   - name: "left_end_effector_link"
#     parent: "left_hand_roll_link"

joint_limits:
  J_waist_pitch: [-0.29671, 0.78540]
  
  J_arm_l_01: [-1.57, 0.9]
  J_arm_l_02: [-1.5, 1.3]
  J_arm_l_03: [0, 2.3]
  J_arm_l_04: [0, 2.9706]
  J_arm_l_05: [-2.96706, 2.96706]
  J_arm_l_06: [-1.83260, 1.83260]
  J_arm_l_07: [-1.04720, 1.04720]

  J_arm_r_01: [-0.9, 1.57]
  J_arm_r_02: [-1.5, 1.3]
  J_arm_r_03: [-2.3, 0]
  J_arm_r_04: [0, 2.9706]
  J_arm_r_05: [-2.96706, 2.96706] 
  J_arm_r_06: [-1.83260, 1.83260]
  J_arm_r_07: [-1.04720, 1.04720]


velocity_limits:
  J_waist_pitch: 0.3
  J_head_yaw: 1.0
  J_head_pitch: 1.0
  J_arm_l_01: 6.283185307179586
  J_arm_l_02: 6.283185307179586
  J_arm_l_03: 6.283185307179586
  J_arm_l_04: 6.283185307179586
  J_arm_l_05: 6.283185307179586
  J_arm_l_06: 6.283185307179586
  J_arm_l_07: 6.283185307179586

  J_arm_r_01: 6.283185307179586
  J_arm_r_02: 6.283185307179586
  J_arm_r_03: 6.283185307179586
  J_arm_r_04: 6.283185307179586
  J_arm_r_05: 6.283185307179586
  J_arm_r_06: 6.283185307179586
  J_arm_r_07: 6.283185307179586

body_scaling_factor: 1.2

position_filter:
  min_cutoff: 0.01
  beta: 1.0

orientation_filter:
  alpha: 0.6

named_links:
  root_link: "link_base"
  left_end_effector_link: "left_end_effector_link"
  right_end_effector_link: "right_end_effector_link"
  head_link: "J_head_pitch"
  left_elbow_pitch_joint: "Link_arm_l_07"
  right_elbow_pitch_joint: "Link_arm_r_07"
  
