defaults:
  - teleop
  - hand: fourier_dexpilot
  - robot: gr1
  - camera: oak
  - _self_


debug: false
debug_hand: false
sim: false
wait_time: 3.0
frequency: 60
use_waist: false
use_head: false
use_depth: false
task_name: "default"


recording:
  enabled: true
  task_name: ${task_name}

upsampler:
  frequency: 120
  gravity_compensation: true
