defaults:
  - hand: fourier
  - robot: gr1
  - camera: oak
  - _self_
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

# robot:
#   urdf_path: "gr1/urdf/GR1T2_fourier_hand_6dof.urdf"
# hand:
#   left:
#     urdf_path: gr1/urdf/fourier_hand_left.urdf
#   right:
#     urdf_path: gr1/urdf/fourier_hand_right.urdf

debug: false
sim: false
wait_time: 5.0
frequency: 50
use_waist: false
use_head: false

recording:
  enabled: false
  task_name: "teleop"

joint_filter:
  min_cutoff: 0.01
  beta: 10.0

hand_filter:
  min_cutoff: 0.001
  beta: 50.0

head_filter:
  alpha: 0.7

upsampler:
  frequency: 120
  gravity_compensation: false

preprocessor:
  hand_type: ${hand.type}
  named_links: ${robot.named_links}

hydra:
  run:
    dir: outputs/${recording.task_name}/${now:%Y-%m-%d_%H-%M-%S}
