defaults:
  - teleop
  - hand: fourier_dexpilot
  - robot: gr1t2
  - camera: oak
  - _self_


debug: false
debug_hand: false
sim: false
wait_time: 3.0
frequency: 60
use_waist: false
use_head: false

joint_filter:
  min_cutoff: 0.001
  beta: 10.0
